### ISSUE TITLE
Can you change fonts/spacing/border radius in themes?

### ISSUE THREAD

**Issue by FancyFurret** [L-Blondy/tw-colors#48] opened 2024-10-10 04:10 UTC
Hi, I would like to create a few themes for my site, and some themes should have different border radiuses/widths, or different fonts, etc. Is this possible with this library? Or does it just support colors? Would it be possible to add other types of data to the themes as well?

**Comment by L-Blondy** [comment] 2024-10-10 07:10
Duplicate of #1

**Closed by L-Blondy** 2024-10-10 07:10 UTC
